export const translateKey = (key: string): string => {
  const translations = {
      projects: 'Proyectos',
      purchaseOrder: 'Orden de Compra',
      address: 'Dirección',
      requestedBy: 'Solicitado Por',
      businessName: 'Nombre de la Empresa',
      contact: 'Contacto',
      phone: 'Teléfono',
      email: 'Correo Electrónico',
      endUser: 'Usuario Final',
      onSiteInspection: 'Inspección en Sitio',
      onSiteAssistance: 'Asistencia en Sitio',
      batteryCapacityTest: 'Prueba de Capacidad de Batería',
      maintenance: 'Mantenimiento',
      correctivo: 'Correctivo',
      other: 'Otro',
      installation: 'Instalación',
      batteryAutonomyTest: 'Prueba de Autonomía de Batería',
      phoneAssistance: 'Asistencia Telefónica',
      arrangementAndStartup: 'Ajuste y Puesta en Marcha',
      type: 'Tipo',
      model: 'Modelo',
      serial: 'Número de Serie',
      input: 'Entrada',
      phases: 'Fases',
      current: 'Corriente',
      output: 'Salida',
      currentOrPower: 'Corriente o Potencia',
      frequency: 'Frecuencia',
      batteryBank: 'Banco de Baterías',
      numberOfBanks: 'Número de Bancos',
      brand: 'Marca',
      capacity: 'Capacidad',
      numberOfCells: 'Número de Celdas',
      date: 'Fecha',
      departureTime: 'Hora de Salida',
      arrivalTime: 'Hora de Llegada',
      startTime: 'Hora de Inicio',
      endTime: 'Hora de Finalización',
      numberOfTechnicians: 'Número de Técnicos',
      technicalLeader: 'Líder Técnico',
      digitalMultimeter: 'Multímetro Digital',
      batteryTester: 'Probador de Baterías',
      torqueWrench: 'Llave de Torque',
      otherInstruments: 'Otros Instrumentos',
      ambientTemperature: 'Temperatura Ambiente',
      relativeHumidity: 'Humedad Relativa',
      clampMeter: 'Pinza Amperimétrica',
      temperatureMeter: 'Termómetro',
      excessiveDust: 'Polvo Excesivo',
      technicalInterventionConform: 'Conformidad de la Intervención Técnica',
      comments: 'Comentarios',
      signature: 'Firma',
      name: 'Nombre',
      id: 'ID',
  } as const;

  return translations[key as keyof typeof translations] || key;
};